/**
 * @file index.ts - Contains class for converting JSON data generated by BuildDocs module into markdown and/or HTML.
 * @access private
 * @namespace {JsonToDocs | build-docs.JsonToDocs}
 * @module JsonToDocs
 * @memberof namespace:build-docs
 */

import { DataItem, ProcessedDataItem } from '../types';

/**
 * @access private
 * @memberof module:JsonToDocs
 * @memberof namespace:build-docs.JsonToDocs
 * @classdesc Converting JSON data generated by BuildDocs module into markdown and/or HTML.
 */
/**
 * Class to convert JSON data to Markdown and HTML
 */
class JsonToDocs {
    data: DataItem[];
    processedData: ProcessedDataItem[];

    /**
     * @param {DataItem[]} data - The JSON data to convert
     */
    constructor(data: DataItem[]) {
        this.data = data;
        this.processedData = this.processData(data);
    }

    /**
     * Process data for easier use
     * @param {DataItem[]} data - The data to process
     * @return {ProcessedDataItem[]} The processed data
     */
    processData(data: DataItem[]): ProcessedDataItem[] {
        return data.map(item => {
            const newItem: ProcessedDataItem = {
                id: item.id,
                fileName: item.fileName,
                filePath: item.filePath,
                createdDate: item.createdDate,
                modifiedDate: item.modifiedDate,
                relatedComments: item.relatedComments,
                doc: {}
            };

            Object.entries(item.doc).forEach(([key, valArray]) => {
                newItem.doc[key] = valArray.map(val => val.description);
            });

            return newItem;
        });
    }

    /**
     * Convert the data to Markdown
     * @return {string} The Markdown string
     * @todo Implement the method
     */
    toMarkdown(): string {
        // Implement the method as before...
        return '';
    }

    /**
     * Convert the data to HTML
     * @return {string} The HTML string
     * @todo Implement the method
     */
    toHtml(): string {
        // Implement the method as before...
        return '';
    }
}


module.exports = JsonToDocs
